# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'ata.ui'
#
# Created by: PyQt5 UI code generator 5.11.3
#
# WARNING! All changes made in this file will be lost!

from PyQt5 import QtCore, QtGui, QtWidgets

class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(821, 518)
        MainWindow.setStyleSheet("")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout_8 = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout_8.setObjectName("verticalLayout_8")
        self.horizontalLayout_15 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_15.setObjectName("horizontalLayout_15")
        self.verticalLayout_7 = QtWidgets.QVBoxLayout()
        self.verticalLayout_7.setObjectName("verticalLayout_7")
        self.horizontalLayout_2 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_2.setObjectName("horizontalLayout_2")
        self.label = QtWidgets.QLabel(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Preferred)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.label.sizePolicy().hasHeightForWidth())
        self.label.setSizePolicy(sizePolicy)
        self.label.setObjectName("label")
        self.horizontalLayout_2.addWidget(self.label)
        self.departamentoCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Expanding, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.departamentoCombo.sizePolicy().hasHeightForWidth())
        self.departamentoCombo.setSizePolicy(sizePolicy)
        self.departamentoCombo.setObjectName("departamentoCombo")
        self.horizontalLayout_2.addWidget(self.departamentoCombo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_2)
        self.horizontalLayout_13 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_13.setObjectName("horizontalLayout_13")
        self.horizontalLayout_10 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_10.setObjectName("horizontalLayout_10")
        self.horizontalLayout_3 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_3.setObjectName("horizontalLayout_3")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setObjectName("label_3")
        self.horizontalLayout_3.addWidget(self.label_3)
        self.convSpin = QtWidgets.QSpinBox(self.centralwidget)
        self.convSpin.setObjectName("convSpin")
        self.horizontalLayout_3.addWidget(self.convSpin)
        self.horizontalLayout_10.addLayout(self.horizontalLayout_3)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_10)
        self.horizontalLayout_12 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_12.setObjectName("horizontalLayout_12")
        self.label_11 = QtWidgets.QLabel(self.centralwidget)
        self.label_11.setObjectName("label_11")
        self.horizontalLayout_12.addWidget(self.label_11)
        self.secLine = QtWidgets.QLineEdit(self.centralwidget)
        self.secLine.setObjectName("secLine")
        self.horizontalLayout_12.addWidget(self.secLine)
        self.horizontalLayout_13.addLayout(self.horizontalLayout_12)
        self.verticalLayout_7.addLayout(self.horizontalLayout_13)
        self.horizontalLayout_8 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_8.setObjectName("horizontalLayout_8")
        self.label_7 = QtWidgets.QLabel(self.centralwidget)
        self.label_7.setObjectName("label_7")
        self.horizontalLayout_8.addWidget(self.label_7)
        self.nomeLine = QtWidgets.QLineEdit(self.centralwidget)
        self.nomeLine.setObjectName("nomeLine")
        self.horizontalLayout_8.addWidget(self.nomeLine)
        self.generoCombo = QtWidgets.QComboBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Minimum)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.generoCombo.sizePolicy().hasHeightForWidth())
        self.generoCombo.setSizePolicy(sizePolicy)
        self.generoCombo.setObjectName("generoCombo")
        self.generoCombo.addItem("")
        self.generoCombo.addItem("")
        self.horizontalLayout_8.addWidget(self.generoCombo)
        self.verticalLayout_7.addLayout(self.horizontalLayout_8)
        self.horizontalLayout_7 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_7.setObjectName("horizontalLayout_7")
        self.label_8 = QtWidgets.QLabel(self.centralwidget)
        self.label_8.setObjectName("label_8")
        self.horizontalLayout_7.addWidget(self.label_8)
        self.tituloLine = QtWidgets.QLineEdit(self.centralwidget)
        self.tituloLine.setObjectName("tituloLine")
        self.horizontalLayout_7.addWidget(self.tituloLine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_7)
        self.horizontalLayout_11 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_11.setObjectName("horizontalLayout_11")
        self.label_10 = QtWidgets.QLabel(self.centralwidget)
        self.label_10.setObjectName("label_10")
        self.horizontalLayout_11.addWidget(self.label_10)
        self.localLine = QtWidgets.QLineEdit(self.centralwidget)
        self.localLine.setObjectName("localLine")
        self.horizontalLayout_11.addWidget(self.localLine)
        self.verticalLayout_7.addLayout(self.horizontalLayout_11)
        self.horizontalLayout_9 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_9.setObjectName("horizontalLayout_9")
        self.horizontalLayout_4 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_4.setObjectName("horizontalLayout_4")
        self.label_4 = QtWidgets.QLabel(self.centralwidget)
        self.label_4.setObjectName("label_4")
        self.horizontalLayout_4.addWidget(self.label_4)
        self.reuniaoDate = QtWidgets.QDateEdit(self.centralwidget)
        self.reuniaoDate.setCalendarPopup(True)
        self.reuniaoDate.setObjectName("reuniaoDate")
        self.horizontalLayout_4.addWidget(self.reuniaoDate)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_4)
        self.horizontalLayout_5 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_5.setObjectName("horizontalLayout_5")
        self.label_5 = QtWidgets.QLabel(self.centralwidget)
        self.label_5.setObjectName("label_5")
        self.horizontalLayout_5.addWidget(self.label_5)
        self.inicioTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.inicioTime.setObjectName("inicioTime")
        self.horizontalLayout_5.addWidget(self.inicioTime)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_5)
        self.horizontalLayout_6 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_6.setObjectName("horizontalLayout_6")
        self.label_6 = QtWidgets.QLabel(self.centralwidget)
        self.label_6.setObjectName("label_6")
        self.horizontalLayout_6.addWidget(self.label_6)
        self.fimTime = QtWidgets.QTimeEdit(self.centralwidget)
        self.fimTime.setObjectName("fimTime")
        self.horizontalLayout_6.addWidget(self.fimTime)
        self.horizontalLayout_9.addLayout(self.horizontalLayout_6)
        self.verticalLayout_7.addLayout(self.horizontalLayout_9)
        self.verticalLayout_3 = QtWidgets.QVBoxLayout()
        self.verticalLayout_3.setObjectName("verticalLayout_3")
        self.horizontalLayout_14 = QtWidgets.QHBoxLayout()
        self.horizontalLayout_14.setObjectName("horizontalLayout_14")
        self.label_9 = QtWidgets.QLabel(self.centralwidget)
        self.label_9.setObjectName("label_9")
        self.horizontalLayout_14.addWidget(self.label_9)
        self.limparButton = QtWidgets.QPushButton(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Fixed, QtWidgets.QSizePolicy.Fixed)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.limparButton.sizePolicy().hasHeightForWidth())
        self.limparButton.setSizePolicy(sizePolicy)
        self.limparButton.setObjectName("limparButton")
        self.horizontalLayout_14.addWidget(self.limparButton)
        self.verticalLayout_3.addLayout(self.horizontalLayout_14)
        self.pautaText = QtWidgets.QTextEdit(self.centralwidget)
        self.pautaText.setObjectName("pautaText")
        self.verticalLayout_3.addWidget(self.pautaText)
        self.verticalLayout_7.addLayout(self.verticalLayout_3)
        self.horizontalLayout_15.addLayout(self.verticalLayout_7)
        self.verticalLayout_2 = QtWidgets.QVBoxLayout()
        self.verticalLayout_2.setObjectName("verticalLayout_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setObjectName("label_2")
        self.verticalLayout_2.addWidget(self.label_2)
        self.horizontalLayout = QtWidgets.QHBoxLayout()
        self.horizontalLayout.setObjectName("horizontalLayout")
        self.groupBox = QtWidgets.QGroupBox(self.centralwidget)
        sizePolicy = QtWidgets.QSizePolicy(QtWidgets.QSizePolicy.Preferred, QtWidgets.QSizePolicy.Expanding)
        sizePolicy.setHorizontalStretch(0)
        sizePolicy.setVerticalStretch(0)
        sizePolicy.setHeightForWidth(self.groupBox.sizePolicy().hasHeightForWidth())
        self.groupBox.setSizePolicy(sizePolicy)
        self.groupBox.setObjectName("groupBox")
        self.verticalLayout_4 = QtWidgets.QVBoxLayout(self.groupBox)
        self.verticalLayout_4.setObjectName("verticalLayout_4")
        self.profText = QtWidgets.QTextEdit(self.groupBox)
        self.profText.setObjectName("profText")
        self.verticalLayout_4.addWidget(self.profText)
        self.horizontalLayout.addWidget(self.groupBox)
        self.verticalLayout = QtWidgets.QVBoxLayout()
        self.verticalLayout.setObjectName("verticalLayout")
        self.groupBox_2 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_2.setObjectName("groupBox_2")
        self.verticalLayout_5 = QtWidgets.QVBoxLayout(self.groupBox_2)
        self.verticalLayout_5.setObjectName("verticalLayout_5")
        self.tecnicosText = QtWidgets.QTextEdit(self.groupBox_2)
        self.tecnicosText.setObjectName("tecnicosText")
        self.verticalLayout_5.addWidget(self.tecnicosText)
        self.verticalLayout.addWidget(self.groupBox_2)
        self.groupBox_3 = QtWidgets.QGroupBox(self.centralwidget)
        self.groupBox_3.setObjectName("groupBox_3")
        self.verticalLayout_6 = QtWidgets.QVBoxLayout(self.groupBox_3)
        self.verticalLayout_6.setObjectName("verticalLayout_6")
        self.alunosText = QtWidgets.QTextEdit(self.groupBox_3)
        self.alunosText.setObjectName("alunosText")
        self.verticalLayout_6.addWidget(self.alunosText)
        self.verticalLayout.addWidget(self.groupBox_3)
        self.horizontalLayout.addLayout(self.verticalLayout)
        self.verticalLayout_2.addLayout(self.horizontalLayout)
        self.horizontalLayout_15.addLayout(self.verticalLayout_2)
        self.verticalLayout_8.addLayout(self.horizontalLayout_15)
        self.buttonBox = QtWidgets.QDialogButtonBox(self.centralwidget)
        self.buttonBox.setStandardButtons(QtWidgets.QDialogButtonBox.Cancel|QtWidgets.QDialogButtonBox.Ok)
        self.buttonBox.setCenterButtons(True)
        self.buttonBox.setObjectName("buttonBox")
        self.verticalLayout_8.addWidget(self.buttonBox)
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "Janela"))
        self.label.setText(_translate("MainWindow", "Departamento"))
        self.label_3.setText(_translate("MainWindow", "Nº da ata:"))
        self.label_11.setText(_translate("MainWindow", "Secretaria:"))
        self.label_7.setText(_translate("MainWindow", "Presidência:"))
        self.generoCombo.setItemText(0, _translate("MainWindow", "[M]"))
        self.generoCombo.setItemText(1, _translate("MainWindow", "[F]"))
        self.label_8.setText(_translate("MainWindow", "Título"))
        self.tituloLine.setText(_translate("MainWindow", "Chefe do Departamento"))
        self.label_10.setText(_translate("MainWindow", "Local:"))
        self.localLine.setText(_translate("MainWindow", "utilizando a Plataforma MConf"))
        self.label_4.setText(_translate("MainWindow", "Data"))
        self.label_5.setText(_translate("MainWindow", "Começo"))
        self.label_6.setText(_translate("MainWindow", "Fim"))
        self.label_9.setText(_translate("MainWindow", "Pauta - um item por linha, sem numerar"))
        self.limparButton.setText(_translate("MainWindow", "Higienizar pautas"))
        self.label_2.setText(_translate("MainWindow", "Lista de presença - um nome por linha"))
        self.groupBox.setTitle(_translate("MainWindow", "Docentes"))
        self.groupBox_2.setTitle(_translate("MainWindow", "Técnicos"))
        self.groupBox_3.setTitle(_translate("MainWindow", "Discentes"))

